import VlibrasPageContent from "./VlibrasPageContent"

export const metadata = {
  title: "Meu Site com VLIBRAS",
  description: "Generated by create next app",
}

export default function Home() {
  return <VlibrasPageContent />
}
